# Generated by Django 2.0a1 on 2017-11-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='articlev2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('title', models.CharField(max_length=16)),
                ('text', models.TextField(max_length=100)),
                ('flag', models.IntegerField()),
                ('getdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ports_data',
            fields=[
                ('ip', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('os', models.CharField(max_length=100)),
                ('hostname', models.CharField(max_length=100)),
                ('ports', models.TextField(max_length=100)),
                ('getdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='search_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('email', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=16)),
                ('flag', models.IntegerField()),
            ],
        ),
    ]
